---
# tasks file for ansible-role-centos-docker

  - name: Include vars of docker.yaml.
    include_vars:
      file: group_vars/docker.yml

  - name: Remove existing docker installations or packages
    yum:
     name: "{{ packages_to_remove }}"
     state: absent

  - name: Install some default software on all new linux machines.
    yum:
      name: yum-utils
      state: present

  - name: Download docker yum repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: '0644'

  - name: Install docker
    yum:
      name: "{{ packages_to_install }}"
      state: present

  - name: Check if docker is running
    service:
      name: docker
      state: started
      enabled: yes

  - name: Adding the user to docker group
    user:
      name: kaaditya
      comment: Kiran Shankar Aaditya
      group: docker    