---
# tasks file for ansible-role-centos-docker

  - name: Remove existing docker installations or packages
    yum:
      name: "{{ packages_to_remove }}"
      state: absent

  - name: Install some pre-flight packages
    yum:
      name: "{{ pre_packages_to_install }}"
      state: present

  - name: Upgrade all packages.
    yum:
      name: '*'
      state: latest

  - name: Install some default software on all new linux machines.
    yum:
      name: yum-utils
      state: present

  - name: Download docker yum repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: '0644'

  - name: Install docker
    yum:
      name: "{{ packages_to_install }}"
      state: present

  - name: Check if docker is running
    service:
      name: docker
      state: started
      enabled: yes

  - name: Creating a docker systemd daemon
    copy:
      src: ../templates/daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: 0644

  - name: Create a docker.service.d systemd directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory

  - name: Restart the docker service and a daemon reload
    systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes
      name: docker

  - name: Adding the user to docker group
    user:
      name: kaaditya
      comment: Kiran Shankar Aaditya
      group: docker    